"""
FitLux Shop product catalog — 120 curated best-sellers across 6 categories.

Every product uses an Amazon search URL (no fixed ASIN), so the listing on
amazon.* always reflects current best-sellers and the user's affiliate tag is
applied automatically by build_amazon_url() in server.py.
"""

# Category metadata used by the API + UI.
CATEGORIES = [
    {"id": "protein",         "label": "Protein, Drinks & Snacks",
     "image": "https://images.unsplash.com/photo-1524649876414-7ca0bcd8b3ff?w=400"},
    {"id": "mens_apparel",    "label": "Men's Workout Wear",
     "image": "https://images.unsplash.com/photo-1646072507419-9f836f8d3f67?w=400"},
    {"id": "womens_apparel",  "label": "Women's Workout Wear",
     "image": "https://images.unsplash.com/photo-1629753897877-522619845842?w=400"},
    {"id": "gym_equipment",   "label": "Dumbbells, Barbells & Weights",
     "image": "https://images.unsplash.com/photo-1589819451091-e62c8d4b63e0?w=400"},
    {"id": "health_supps",    "label": "Health Supplements",
     "image": "https://images.unsplash.com/photo-1763668177859-0ed5669a795e?w=400"},
    {"id": "calisthenics",    "label": "Calisthenics Equipment",
     "image": "https://images.unsplash.com/photo-1620188552551-9f98661cbef7?w=400"},
]

# Per-category image rotation so the 20 product cards look varied.
_IMG = {
    "protein": [
        "https://images.unsplash.com/photo-1524649876414-7ca0bcd8b3ff?w=400",
        "https://images.pexels.com/photos/29107585/pexels-photo-29107585.jpeg?auto=compress&w=400",
        "https://images.pexels.com/photos/14963236/pexels-photo-14963236.jpeg?auto=compress&w=400",
    ],
    "mens_apparel": [
        "https://images.unsplash.com/photo-1646072507419-9f836f8d3f67?w=400",
        "https://images.unsplash.com/photo-1608217002058-2e45c33b6c2c?w=400",
    ],
    "womens_apparel": [
        "https://images.unsplash.com/photo-1629753897877-522619845842?w=400",
        "https://images.unsplash.com/photo-1760509370911-b134eaa23d5a?w=400",
    ],
    "gym_equipment": [
        "https://images.unsplash.com/photo-1589819451091-e62c8d4b63e0?w=400",
        "https://images.unsplash.com/photo-1653927956711-f2222a45e040?w=400",
    ],
    "health_supps": [
        "https://images.unsplash.com/photo-1763668177859-0ed5669a795e?w=400",
        "https://images.unsplash.com/photo-1763668444855-401b58dceb20?w=400",
        "https://images.pexels.com/photos/29107657/pexels-photo-29107657.jpeg?auto=compress&w=400",
    ],
    "calisthenics": [
        "https://images.unsplash.com/photo-1620188552551-9f98661cbef7?w=400",
        "https://images.unsplash.com/photo-1579364046732-c21c2177730d?w=400",
    ],
}


def _img(cat: str, idx: int) -> str:
    pool = _IMG[cat]
    return pool[idx % len(pool)]


# Compact tuple format → expanded into product dicts:
# (id_suffix, name, tagline, search, price_usd, [benefits...])
_PROTEIN = [
    ("on-gold",   "Optimum Nutrition Gold Standard Whey",  "24g whey protein per scoop · world's #1",
     "Optimum Nutrition Gold Standard Whey Protein 5lb", "£49.99",
     ["24g protein", "Fast absorbing", "World's #1 selling whey"],
     "B000QSNYGI",
     "https://m.media-amazon.com/images/I/71gR9O4i6cL._AC_SX569_.jpg"),
    ("myprotein", "MyProtein Impact Whey Protein",          "21g per serving · 60+ flavours",
     "MyProtein Impact Whey Protein", "$39.99",
     ["High protein", "Affordable", "Bestseller"]),
    ("dymatize",  "Dymatize ISO100 Hydrolyzed",             "25g hydrolyzed whey isolate",
     "Dymatize ISO100 Hydrolyzed Whey Isolate Protein", "$64.99",
     ["Lactose-free", "Hydrolyzed", "Fast recovery"]),
    ("syntha6",   "BSN Syntha-6 Protein Powder",            "22g multi-source blend",
     "BSN Syntha-6 Protein Powder", "$44.99",
     ["Sustained release", "Great taste", "Versatile"]),
    ("nitrotech", "MuscleTech Nitro-Tech Whey",             "30g protein + creatine",
     "MuscleTech Nitro-Tech 100% Whey Gold", "$54.99",
     ["Protein + creatine", "Strength gains", "30g per scoop"]),
    ("naked",     "Naked Whey Grass-Fed Protein",           "Single ingredient, grass-fed",
     "Naked Whey Grass Fed Whey Protein 5lb", "$89.99",
     ["Grass-fed", "No additives", "Pure"]),
    ("godlife",   "Garden of Life Sport Plant Protein",     "30g organic plant protein",
     "Garden of Life Sport Organic Plant Based Protein", "$54.99",
     ["Plant-based", "Organic", "30g protein"]),
    ("vega",      "Vega Sport Premium Plant Protein",       "30g plant protein + BCAAs",
     "Vega Sport Premium Plant Protein Powder", "$49.99",
     ["Vegan", "BCAAs", "30g plant protein"]),
    ("quest",     "Quest Nutrition Protein Bars",           "20g protein · 1g sugar",
     "Quest Nutrition Protein Bars Variety Pack", "$26.99",
     ["20g protein", "Low sugar", "High fibre"]),
    ("grenade",   "Grenade Carb Killa Protein Bars",        "23g protein · low carb",
     "Grenade Carb Killa High Protein Bar", "$29.99",
     ["23g protein", "Low carb", "Indulgent flavours"]),
    ("barebells", "Barebells Protein Bars",                 "20g protein · zero added sugar",
     "Barebells Protein Bars Variety Pack", "$27.99",
     ["20g protein", "Zero added sugar", "Soft texture"]),
    ("pureprot",  "Pure Protein Bars Variety Pack",         "20g protein · gluten-free",
     "Pure Protein Bars Variety Pack", "$15.99",
     ["20g protein", "Gluten-free", "Affordable"]),
    ("premier",   "Premier Protein Shakes Ready-to-Drink",  "30g protein · 1g sugar",
     "Premier Protein Shakes 30g Protein Variety", "$31.99",
     ["30g protein", "Ready to drink", "Low sugar"]),
    ("fairlife",  "Fairlife Core Power Protein Shake",      "26g protein · post-workout",
     "Fairlife Core Power High Protein Milk Shake", "$33.99",
     ["26g protein", "Post-workout", "Real milk"]),
    ("musclemilk","Muscle Milk Genuine Protein Shake",      "25g protein · ready-to-drink",
     "Muscle Milk Genuine Protein Shake", "$28.99",
     ["25g protein", "Convenient", "Lactose-free"]),
    ("rxbar",     "RXBAR Whole Food Protein Bars",          "12g egg-white protein",
     "RXBAR Whole Food Protein Bar Variety", "$24.99",
     ["Whole food", "12g protein", "No BS"]),
    ("builtbar",  "Built Bar Protein Bars",                 "17g protein · 100 cal",
     "Built Bar Protein Bars Variety Pack", "$32.99",
     ["17g protein", "Low calorie", "Chocolate coated"]),
    ("clif",      "Clif Builders Protein Bars",             "20g plant-based protein",
     "Clif Builders Protein Bar Variety", "$23.99",
     ["20g protein", "Plant based", "Long-lasting energy"]),
    ("sis-whey",  "Science in Sport Whey20 Protein",        "20g whey · sports formulated",
     "Science in Sport SIS Whey20 Protein Powder", "$44.99",
     ["20g whey", "Sports tested", "Easy mix"]),
    ("phddiet",   "PhD Nutrition Diet Whey Lean",           "17g protein · low calorie",
     "PhD Nutrition Diet Whey Lean Protein Powder", "$39.99",
     ["17g protein", "Low calorie", "Lean physique"]),
]

_MENS = [
    ("ua-tech",   "Under Armour Men's Tech 2.0 T-Shirt",   "Sweat-wicking · loose fit",
     "Under Armour Men's Tech 2.0 Short Sleeve T Shirt", "$25.00",
     ["Sweat-wicking", "Loose fit", "Bestseller"]),
    ("nike-shorts","Nike Men's Dri-FIT Training Shorts",    "Dri-FIT · 7 inch inseam",
     "Nike Men's Dri-FIT Training Shorts", "$30.00",
     ["Dri-FIT", "Lightweight", "Stretch waistband"]),
    ("adidas-tiro","Adidas Men's Tiro Training Pants",      "Slim · Aeroready",
     "Adidas Men's Tiro Track Pants", "$45.00",
     ["Aeroready", "Slim fit", "Side pockets"]),
    ("puma-tee",  "Puma Men's Performance Tee",             "Lightweight performance tee",
     "Puma Men's Performance Short Sleeve T Shirt", "$22.00",
     ["Quick-dry", "Athletic fit", "Breathable"]),
    ("champion-h","Champion Men's Powerblend Hoodie",       "Reduced-pill fleece",
     "Champion Men's Powerblend Pullover Hoodie", "$45.00",
     ["Heavyweight fleece", "Soft inside", "Reduced pilling"]),
    ("rbk-shorts","Reebok Men's Workout Ready Shorts",      "Stretch · breathable",
     "Reebok Men's Workout Ready Shorts", "$24.00",
     ["Stretch fabric", "Mesh panels", "Side pockets"]),
    ("hanes-cool","Hanes Men's Cool DRI Performance Tee",   "Moisture-wicking · 4-pack",
     "Hanes Men's Cool DRI Performance T Shirt 4 Pack", "$22.00",
     ["UPF 50", "Moisture-wicking", "Multi-pack"]),
    ("ua-comp",   "Under Armour Men's HeatGear Compression","Compression · sweat-wicking",
     "Under Armour Men's HeatGear Armour Compression Shorts", "$28.00",
     ["Compression", "HeatGear", "9 inch inseam"]),
    ("nike-pro",  "Nike Men's Pro Compression Tights",      "Pro Dri-FIT · full length",
     "Nike Men's Pro Dri-FIT Tight", "$45.00",
     ["Compression fit", "Dri-FIT", "Squat-proof"]),
    ("ch-long",   "Champion Men's Long-Sleeve Performance", "Long-sleeve · double dry",
     "Champion Men's Long Sleeve Performance T Shirt", "$22.00",
     ["Double Dry", "Stretch", "UPF 30"]),
    ("ad-tank",   "Adidas Men's Essentials 3-Stripes Tank", "Cotton blend tank",
     "Adidas Men's Essentials 3 Stripes Tank Top", "$25.00",
     ["3-Stripes design", "Soft cotton", "Athletic cut"]),
    ("ua-tac",    "Under Armour Men's Tactical Tech Tee",   "Tactical · long fit",
     "Under Armour Men's Tactical Tech T Shirt", "$25.00",
     ["Tactical fit", "Anti-odor", "Anti-pick"]),
    ("nk-therma", "Nike Men's Therma-FIT Hoodie",           "Therma-FIT · pullover",
     "Nike Men's Therma-FIT Pullover Hoodie", "$60.00",
     ["Therma-FIT warmth", "Soft fleece", "Kangaroo pocket"]),
    ("ad-jogger", "Adidas Men's Aeroready Joggers",         "Tapered · Aeroready",
     "Adidas Men's Essentials Tapered Cuff Pants", "$45.00",
     ["Aeroready", "Tapered", "Zip pockets"]),
    ("puma-tank", "Puma Men's Essentials Logo Tank",        "Cotton tank · gym fit",
     "Puma Men's Essentials Logo Tank Top", "$22.00",
     ["Soft cotton", "Logo print", "Loose fit"]),
    ("rbk-hood",  "Reebok Men's Identity Hoodie",           "Pullover · bestseller",
     "Reebok Men's Identity Pullover Hoodie", "$40.00",
     ["Soft fleece", "Drawstring hood", "Kangaroo pocket"]),
    ("ch-mesh",   "Champion Men's Mesh Athletic Shorts",    "Mesh · 9 inch inseam",
     "Champion Men's Mesh Athletic Shorts", "$15.00",
     ["Mesh fabric", "Lightweight", "Affordable"]),
    ("ua-rival",  "Under Armour Men's Rival Fleece Joggers","Rival fleece · cuffed",
     "Under Armour Men's Rival Fleece Joggers", "$45.00",
     ["Rival fleece", "Cuffed ankles", "Side pockets"]),
    ("nk-air",    "Nike Men's Air Sportswear Tee",          "Air logo · classic fit",
     "Nike Men's Air Sportswear T Shirt", "$30.00",
     ["Soft cotton", "Air logo print", "Classic fit"]),
    ("nb-essent", "New Balance Men's Essentials Stacked",    "Stacked logo · cotton tee",
     "New Balance Men's Essentials Stacked Logo Cotton T Shirt", "$22.00",
     ["100% cotton", "Stacked logo", "Crew neck"]),
]

_WOMENS = [
    ("crz-leg",   "CRZ YOGA Women's High-Waist Leggings",  "Naked feel · 25 inch",
     "CRZ YOGA Women's Naked Feeling High Waist Leggings", "$32.00",
     ["Squat-proof", "Naked feel", "High waist"]),
    ("lulu-train","Lululemon-style Wunder Train Tights",   "Buttery soft · sweat-wicking",
     "Lululemon Wunder Train High Rise Tight", "$98.00",
     ["Buttery soft", "Pocket detail", "Premium"]),
    ("ua-vneck",  "Under Armour Women's Tech V-Neck",       "Loose · Tech 2.0",
     "Under Armour Women's Tech V Neck T Shirt", "$25.00",
     ["Tech fabric", "V-neck", "Loose fit"]),
    ("nike-one",  "Nike Women's One Tights",               "Mid-rise · Dri-FIT",
     "Nike Women's One Mid Rise Tight", "$50.00",
     ["Dri-FIT", "Mid-rise", "Squat-proof"]),
    ("adi-bra",   "Adidas Women's 3-Stripes Sports Bra",    "Light support · pull-over",
     "Adidas Women's Training 3 Stripes Sports Bra", "$25.00",
     ["Light support", "3 Stripes", "Pull over"]),
    ("byond-bra", "Beyond Yoga Spacedye Caught in the Midi","Midi · spacedye fabric",
     "Beyond Yoga Spacedye Caught in the Midi Bra", "$60.00",
     ["Spacedye", "Midi length", "Soft hand"]),
    ("athleta",   "Athleta-style Salutation Stash Tight",   "Pocket leggings · stretch",
     "Athleta Salutation Stash Pocket Tight", "$89.00",
     ["Side pockets", "Stretch fabric", "Premium feel"]),
    ("ch-orig",   "Champion Women's Originals Hoodie",      "Soft fleece pullover",
     "Champion Women's Authentic Originals Hoodie", "$40.00",
     ["Soft fleece", "Drawcord hood", "Pullover"]),
    ("rbk-tights","Reebok Women's Workout Ready Tights",    "Hi-rise · stretch",
     "Reebok Women's Workout Ready Tights", "$30.00",
     ["High rise", "Compression", "Stretch"]),
    ("puma-leg",  "Puma Women's Essentials Logo Leggings",  "Mid-rise · cotton blend",
     "Puma Women's Essentials Logo Leggings", "$27.00",
     ["Cotton blend", "Mid-rise", "Logo print"]),
    ("yvette",    "Yvette Women's High-Impact Sports Bra", "Padded · racerback",
     "Yvette Women's High Impact Sports Bra Padded", "$28.00",
     ["High impact", "Padded", "Racerback"]),
    ("shefit",    "SHEFIT Ultimate Sports Bra",            "High-impact · adjustable",
     "SHEFIT Ultimate Sports Bra", "$75.00",
     ["High impact", "Adjustable", "Locked-down support"]),
    ("syrokan",   "SYROKAN Women's High-Impact Bra",        "Wirefree · plus sizes",
     "SYROKAN Women's High Impact Sports Bra", "$26.00",
     ["High impact", "Wirefree", "Plus sizes"]),
    ("heath-yoga","Heathyoga Bootcut Yoga Pants",           "Bootcut · pockets",
     "Heathyoga Women's Bootcut Yoga Pants With Pockets", "$32.00",
     ["Bootcut", "Pockets", "Stretch"]),
    ("promover",  "Promover Women's Athletic Skort",        "2-in-1 skort · pockets",
     "Promover Women's Athletic Skort With Pockets", "$28.00",
     ["2-in-1 skort", "Pockets", "Tennis & gym"]),
    ("baleaf-jog","Baleaf Women's Workout Joggers",         "Tapered · pockets",
     "Baleaf Women's Workout Joggers With Pockets", "$32.00",
     ["Tapered", "Pockets", "Drawstring"]),
    ("gym-people","THE GYM PEOPLE Women's Lounge Sweatpants","Open-bottom sweats",
     "THE GYM PEOPLE Women's Lounge Sweatpants", "$30.00",
     ["Open bottom", "Drawstring", "Loose fit"]),
    ("ododos",    "ODODOS Women's Cross-Waist Yoga Leggings","Cross waist · 4-way stretch",
     "ODODOS Women's Cross Waist Yoga Leggings", "$26.00",
     ["Cross waist", "4-way stretch", "Squat-proof"]),
    ("ch-tank",   "Champion Women's Authentic Tank Top",    "Cotton tank · classic",
     "Champion Women's Authentic Jersey Tank Top", "$15.00",
     ["100% cotton", "Classic fit", "Affordable"]),
    ("hanes-coolw","Hanes Women's Cool DRI Performance Tee","Moisture-wicking · UPF 50",
     "Hanes Women's Cool DRI Performance T Shirt", "$10.00",
     ["UPF 50", "Cool DRI", "Affordable"]),
]

_GYM = [
    ("bowflex552","Bowflex SelectTech 552 Adjustable Dumbbells","5–52.5 lb · pair",
     "Bowflex SelectTech 552 Adjustable Dumbbells", "$429.00",
     ["Adjustable 5–52.5 lb", "Space-saving", "Replaces 15 sets"]),
    ("powerblock","PowerBlock Elite USA Adjustable Dumbbells","5–50 lb · pair",
     "PowerBlock Elite USA Adjustable Dumbbells", "$329.00",
     ["Stackable design", "5–50 lb", "Made in USA"]),
    ("y4a-vinyl", "Yes4All Vinyl Coated Dumbbells",        "Hex shape · pair",
     "Yes4All Vinyl Coated Hex Dumbbells", "$45.00",
     ["Vinyl coated", "Hex shape", "Pair"]),
    ("cap-hex",   "CAP Barbell Hex Dumbbells",             "Cast iron · rubber coated",
     "CAP Barbell Cast Iron Hex Dumbbell", "$50.00",
     ["Rubber coating", "Cast iron", "Anti-roll"]),
    ("amz-hex",   "AmazonBasics Rubber Encased Hex Dumbbells","Rubber encased · pair",
     "Amazon Basics Rubber Encased Hex Hand Dumbbell", "$65.00",
     ["Rubber encased", "Anti-roll", "Sold as pair"]),
    ("rogue-bar", "Rogue Echo Bar 2.0",                    "Olympic 7' · 28.5mm",
     "Rogue Echo Bar 2.0 Olympic Barbell", "$295.00",
     ["1000 lb tested", "Olympic 7 ft", "28.5 mm"]),
    ("cap-oly",   "CAP Barbell Olympic 2-Inch Bar",        "7' Olympic barbell",
     "CAP Barbell Olympic 2 Inch Bar 7 Foot", "$129.00",
     ["7 ft Olympic", "Beginner friendly", "Affordable"]),
    ("spri-ankle","SPRI Ankle Weights",                    "Adjustable · pair",
     "SPRI Adjustable Ankle Weights Pair", "$30.00",
     ["Adjustable", "Comfort fit", "Pair"]),
    ("bowflex109","Bowflex SelectTech 1090 Dumbbells",     "10–90 lb · pair",
     "Bowflex SelectTech 1090 Adjustable Dumbbells", "$799.00",
     ["10–90 lb", "Space saving", "Replaces 17 sets"]),
    ("nuobell",   "Nüobell Adjustable Dumbbells",          "Premium · 5–80 lb",
     "Nuobell 80 LB Adjustable Dumbbells", "$849.00",
     ["Premium build", "Quick adjust", "5–80 lb"]),
    ("spri-plates","SPRI Olympic Weight Plates",           "Rubber coated · pair",
     "SPRI Olympic Rubber Weight Plates", "$120.00",
     ["Rubber coated", "Olympic 2-inch", "Pair"]),
    ("cap-plates","CAP Barbell Cast Iron Plates",          "Standard 1-inch plates",
     "CAP Barbell Cast Iron Weight Plates", "$95.00",
     ["Cast iron", "Hammertone finish", "Various weights"]),
    ("marcy-curl","Marcy Olympic Curl Bar",                "EZ curl · 28 lb",
     "Marcy Olympic Curl Bar with Spring Collars", "$85.00",
     ["EZ curl angle", "Olympic 2-inch", "Includes collars"]),
    ("y4a-kett",  "Yes4All Cast Iron Kettlebell",          "Solid cast · multiple weights",
     "Yes4All Cast Iron Kettlebell", "$45.00",
     ["Cast iron", "Painted finish", "Smooth handle"]),
    ("amz-kett",  "AmazonBasics Cast Iron Kettlebell",     "Solid cast · single piece",
     "Amazon Basics Cast Iron Kettlebell", "$45.00",
     ["Single-piece cast", "Vinyl coated", "Affordable"]),
    ("cap-kett",  "CAP Barbell Coated Kettlebell",         "Color coded · cast iron",
     "CAP Barbell Coated Cast Iron Kettlebell", "$50.00",
     ["Color coded", "Cast iron", "Wide handle"]),
    ("rep-bench", "Rep Fitness AB-3000 Bench",             "FID adjustable bench",
     "Rep Fitness AB 3000 Adjustable Bench", "$269.00",
     ["FID adjustable", "1000 lb capacity", "Premium build"]),
    ("flybird",   "FLYBIRD Adjustable Weight Bench",       "Folding · 7 positions",
     "FLYBIRD Adjustable Weight Bench Folding", "$129.00",
     ["7 back positions", "Folding", "650 lb capacity"]),
    ("cap-rack",  "CAP Barbell Power Rack Strength Cage",  "Power rack with pull-up bar",
     "CAP Barbell Power Rack Strength Cage", "$329.00",
     ["Power rack", "Pull-up bar", "Safety pins"]),
    ("sunny-tower","Sunny Health & Fitness Power Tower",   "Pull-up + dip + pushup tower",
     "Sunny Health and Fitness Power Tower", "$159.00",
     ["Pull-up + dip + pushup", "Padded", "Stable base"]),
]

_HEALTH = [
    ("on-creat",  "Optimum Nutrition Micronized Creatine", "5g micronized · unflavored",
     "Optimum Nutrition Micronized Creatine Monohydrate Powder", "$24.99",
     ["5g creatine monohydrate", "Micronized", "Unflavoured"]),
    ("bulk-creat","Bulk Pure Creatine Monohydrate",        "Pure creatine · 500g",
     "Bulk Creatine Monohydrate Powder Pure", "$22.99",
     ["Pure creatine", "500g pouch", "No fillers"]),
    ("ph-shilajit","Pure Himalayan Shilajit Resin",        "Authentic high-altitude resin",
     "Pure Himalayan Shilajit Resin Authentic", "$34.99",
     ["Fulvic acid rich", "Lab tested", "Energy & vitality"]),
    ("nat-shilajit","Naturals Origin Shilajit Pure",       "Pure mineral resin",
     "Naturals Origin Shilajit Pure Resin", "$29.99",
     ["100% pure", "Mineral rich", "Lab verified"]),
    ("hd-lions",  "Host Defense Lion's Mane Capsules",      "60ct · organic mushroom",
     "Host Defense Lions Mane Mushroom Capsules", "$29.99",
     ["Organic mushroom", "Cognitive support", "60 capsules"]),
    ("rm-lions",  "Real Mushrooms Lion's Mane Extract",     "Hot water extracted",
     "Real Mushrooms Lions Mane Mushroom Extract", "$29.99",
     ["Hot water extracted", "10:1 ratio", "Vegan"]),
    ("maju-sea",  "Maju Sea Moss Capsules",                "Wildcrafted · 1500mg",
     "Maju Sea Moss Capsules Wildcrafted", "$24.99",
     ["Wildcrafted", "1500 mg per serving", "92 minerals"]),
    ("ct-seamoss","Caribbean Treasures Sea Moss Gel",      "Wildcrafted gel · raw",
     "Caribbean Treasures Wildcrafted Sea Moss Gel", "$19.99",
     ["Raw gel", "Wildcrafted", "Multi-purpose"]),
    ("him-ashwa", "Himalaya Organic Ashwagandha",          "Organic root · 60ct",
     "Himalaya Organic Ashwagandha", "$15.99",
     ["Organic root", "Stress support", "60 caplets"]),
    ("nutri-ashwa","NutriRise Ashwagandha Root Powder",    "1300mg · KSM-66 root",
     "NutriRise Ashwagandha Capsules 1300mg", "$22.99",
     ["1300 mg", "KSM-66 root", "120 capsules"]),
    ("ksm66",     "KSM-66 Ashwagandha by Nutricost",       "Patented KSM-66 extract",
     "Nutricost KSM 66 Ashwagandha Capsules", "$19.99",
     ["Patented KSM-66", "600mg per cap", "Lab verified"]),
    ("doc-mag",   "Doctor's Best High-Absorption Magnesium","Glycinate · 240ct",
     "Doctors Best High Absorption Magnesium Glycinate", "$24.99",
     ["High absorption", "Magnesium glycinate", "240 tablets"]),
    ("nm-d3",     "Nature Made Vitamin D3 5000 IU",        "USP verified · 180ct",
     "Nature Made Vitamin D3 5000 IU 180 Softgels", "$12.99",
     ["5000 IU", "USP verified", "Bone health"]),
    ("now-thean", "NOW Foods L-Theanine 200mg",            "Calm focus · 120ct",
     "NOW Foods L Theanine 200 mg", "$19.99",
     ["L-Theanine 200mg", "Calm focus", "Vegan"]),
    ("sr-tur",    "Sports Research Turmeric Curcumin",     "Organic · BioPerine",
     "Sports Research Turmeric Curcumin Organic BioPerine", "$22.99",
     ["Organic turmeric", "Bioperine added", "Joint support"]),
    ("pe-mag",    "Pure Encapsulations Magnesium Glycinate","Hypoallergenic formula",
     "Pure Encapsulations Magnesium Glycinate", "$28.99",
     ["Hypoallergenic", "Glycinate form", "180 caps"]),
    ("nn-omega",  "Nordic Naturals Ultimate Omega",         "1280mg EPA+DHA",
     "Nordic Naturals Ultimate Omega 1280mg", "$32.99",
     ["1280 mg omega-3", "Triglyceride form", "Lemon flavoured"]),
    ("god-bcomp", "Garden of Life Vitamin Code Raw B-Complex","Whole food B vitamins",
     "Garden of Life Vitamin Code Raw B Complex", "$26.99",
     ["Whole food", "Raw vitamins", "Energy support"]),
    ("bs-betal",  "BulkSupplements Beta-Alanine Powder",   "100g pouch · pure",
     "Bulk Supplements Beta Alanine Powder", "$14.99",
     ["Pure beta-alanine", "Endurance", "Lab tested"]),
    ("now-ashwa", "NOW Foods Ashwagandha Extract",          "450mg · root extract",
     "NOW Foods Ashwagandha 450mg Capsules", "$15.99",
     ["450 mg per cap", "Standardized extract", "Adaptogen"]),
]

_CALI = [
    ("iron-gym",  "Iron Gym Doorway Pull-Up Bar",          "Total Upper Body Workout Bar",
     "Iron Gym Total Upper Body Workout Bar", "$29.99",
     ["No screws", "Total upper body", "Bestseller"]),
    ("perfect",   "Perfect Fitness Multi-Gym Doorway Bar", "Multi-grip pull-up bar",
     "Perfect Fitness Multi Gym Doorway Pull Up Bar", "$49.99",
     ["Multi-grip", "Foam padding", "Easy install"]),
    ("prosource", "ProsourceFit Multi-Grip Pull-Up Bar",   "Heavy-duty doorway",
     "ProsourceFit Multi Grip Pull Up Bar", "$32.99",
     ["Multi-grip", "300 lb capacity", "Foam padded"]),
    ("sport-push","Sportneer Push-Up Handles",             "Foam grips · stable",
     "Sportneer Push Up Bars Handles", "$19.99",
     ["Foam grips", "Stable base", "Wrist friendly"]),
    ("wl-push",   "WeightLift Push Up Bars",               "Steel · non-slip base",
     "WeightLift Push Up Bars Steel", "$22.99",
     ["Steel construction", "Non-slip base", "Pair"]),
    ("lebert",    "Lebert Equalizer Parallel Bars",        "Pro dip & row bars",
     "Lebert Equalizer Total Body Strengthener", "$169.00",
     ["Dip + row + pushup", "400 lb capacity", "Pro grade"]),
    ("sunny-pt2", "Sunny Health Power Tower",              "Pull-up + dip station",
     "Sunny Health and Fitness Power Tower", "$159.00",
     ["Pull-up + dip", "Stable", "Padded grips"]),
    ("stamina-pt","Stamina Power Tower",                   "Compact tower · home gym",
     "Stamina Power Tower for Pull Ups Dips", "$199.00",
     ["Compact", "Pull-up + dip", "Padded backrest"]),
    ("tribe-dip", "Tribe WOD Dip Station",                 "Free-standing dip bars",
     "Tribe WOD Free Standing Dip Bars", "$249.00",
     ["Free-standing", "Heavy duty", "Adjustable height"]),
    ("bs-vkr",    "Body Solid Powerline Vertical Knee Raise","Knee raise + dip + pull-up",
     "Body Solid Powerline Vertical Knee Raise", "$329.00",
     ["3 in 1", "Heavy duty", "Padded"]),
    ("ab-carver", "Perfect Fitness Ab Carver Pro Roller",  "Wide carbon-steel wheel",
     "Perfect Fitness Ab Carver Pro Roller", "$39.99",
     ["Wide wheel", "Resistance spring", "Knee pad included"]),
    ("amz-roll",  "AmazonBasics Ab Roller Wheel",          "Dual wheel · knee pad",
     "Amazon Basics Ab Wheel Roller", "$19.99",
     ["Dual wheel", "Stable", "Includes knee pad"]),
    ("vins-roll", "Vinsguir Ab Roller",                    "Wide stance · stable",
     "Vinsguir Ab Roller Wheel", "$22.99",
     ["Wide stance", "Knee pad", "Bestseller"]),
    ("sport-roll","Sportneer Ab Roller Wheel Set",         "Roller + handles + knee pad",
     "Sportneer Ab Roller Wheel Set With Knee Pad", "$29.99",
     ["Full set", "Knee pad", "Multi-grip"]),
    ("ig-straps", "Iron Gym Ab Straps Heavy Duty",         "Pull-up bar ab straps",
     "Iron Gym Ab Straps Heavy Duty", "$29.99",
     ["Pull-up bar attach", "Padded", "Heavy duty"]),
    ("spri-bands","SPRI Resistance Bands Set",             "Tube bands · 5 levels",
     "SPRI Resistance Bands Set Xertube", "$45.00",
     ["5 resistance levels", "Door anchor", "Travel friendly"]),
    ("body-bands","Bodylastics Resistance Bands",          "Anti-snap clip bands",
     "Bodylastics Resistance Bands Set", "$59.99",
     ["Anti-snap", "Stackable", "Up to 142 lb"]),
    ("wod-bands", "WODFitters Pull-Up Assistance Bands",   "Loop bands · 4-pack",
     "WODFitters Pull Up Assistance Bands", "$39.99",
     ["Pull-up assist", "4 resistance levels", "Loop bands"]),
    ("gym-straps","Gymreapers Lifting Straps",             "Padded · cotton",
     "Gymreapers Lifting Straps Padded", "$14.99",
     ["Padded neoprene", "Cotton straps", "Heavy duty"]),
    ("versa-pro", "Versa Gripps Pro Lifting Straps",       "Pro lifting grips",
     "Versa Gripps PRO Lifting Straps", "$59.99",
     ["Hands-free grip", "Made in USA", "Pro lifters"]),
]


def _build(cat: str, items: list) -> list:
    out = []
    for idx, t in enumerate(items):
        # Tuples can be (slug, name, tagline, search, price, benefits) OR
        # (slug, name, tagline, search, price, benefits, asin, image_url) when
        # the product has been verified with a real Amazon ASIN + image.
        slug, name, tagline, search, price, benefits = t[:6]
        asin = t[6] if len(t) > 6 else None
        custom_image = t[7] if len(t) > 7 else None
        out.append({
            "id": f"{cat}-{slug}",
            "name": name,
            "tagline": tagline,
            "description": tagline,
            "price": price,
            "category": cat,
            "image": custom_image or _img(cat, idx),
            "asin": asin,
            "search": search,
            "benefits": benefits,
            "verified": bool(asin),
        })
    return out


SEED_PRODUCTS = (
    _build("protein", _PROTEIN)
    + _build("mens_apparel", _MENS)
    + _build("womens_apparel", _WOMENS)
    + _build("gym_equipment", _GYM)
    + _build("health_supps", _HEALTH)
    + _build("calisthenics", _CALI)
)
